# Docker Compose

# docker-compose.yml format version
version: '3'

# Define services
services:
    # Python Development Container
    python-dev:
        # Use Dockerfile in current folder
        build: .
        # Mount ros-dev folder on host to app folder in container
        volumes:
            - ./control:/app/control
            - ./dataset:/app/dataset
            - ./localization:/app/localization
            - ./planning:/app/planning
            - ./semantic:/app/semantic
            - ./visualization:/app/visualization
        # Set DISPLAY variable and network mode for GUIs
        environment:
            - DISPLAY=${IP_ADDRESS}:0.0
        network_mode: "host"
        # Set working directory in container to app folder
        working_dir: /app
